### ISSUE TITLE
integrate to citros

### ISSUE THREAD

**Issue by iftahnaf** [citros-garden/turtlebot3#3]
hi @gtep96,

We merged the `updates` branch.

please integrate to citros:

1. build the [production dockerfile](https://github.com/citros-garden/turtlebot3/blob/main/Dockerfile) locally.
2. check that it's running locally on your PC (it may need 1.5 minutes to launch)
3. push the new image to the cloud
4. sync with CITROS
5. launch a simulation with `timeout` of at least 3 [min].

Thanks

**Comment by gtep96** [comment]
Done. I needed to change bot model from waffle to burger and comment out one line in the devcontainer.json to make it work on Mac.
